version: '3'

services:
  zookeeper:
    image: zookeeper
    ports:
      - 2182:2182
    container_name: zookeeper

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFAK_CREATE_TOPIC: "topic:1:3"



